### ISSUE TITLE
Rebrand site for "State & Local Governments"?

### ISSUE THREAD

**Issue by mheadd** [18F/state-faq#20]
The information on this site would be super helpful not only for state governments, but for municipal governments as well (or transportation authorities, planning commissions and any public sector entity).  Even though the content on the site is derived from our work with states, there's nothing that prevents governments at other levels from using it, right?

Would it be worth modifying the site title, or may be just making a note somewhere prominently that this information can be used for any government?

Just a thought.

**Comment by mgwalker** [comment]
That sounds like a good idea to me.  @robincarnahan do you have thoughts?

**Comment by zacharycohn** [comment]
merged @mgwalker 's pull request.
