### ISSUE TITLE
Responsive issues

### ISSUE THREAD

**Issue by zacharycohn** [18F/state-faq#22]
![image](https://cloud.githubusercontent.com/assets/614963/20353015/6c0ccd70-abe7-11e6-84f8-2fa24dce2359.png)

@jtag reports the site doesn't display correctly on an iPhone 5s.

**Comment by konklone** [comment]
Same on my Nexus 5X.

![screenshot_20161117-104751](https://cloud.githubusercontent.com/assets/4592/20403630/93eaacc0-accf-11e6-9d69-6a9dc5bfc05d.png)

**Comment by mgwalker** [comment]
If we still intend to wrap the content from this site into the [modular contracting site](https://modularcontracting.18f.gov/), does it make sense to spend time fixing it?  It seems best use of time to me to move the content to the "real" site.

Someone who knows what they're doing could probably fix the responsiveness issues in just a few minutes, but it'd likely take me all day. 😛

**Comment by zacharycohn** [comment]
Good point. I may work on that this week.
