### ISSUE TITLE
We have heard several risks to the waterfall approach. What are the risks to agile approach?

### ISSUE THREAD

**Issue by jposi** [18F/state-faq#6]
Question still needs to be answered.

**Comment by porta-antiporta** [comment]
https://github.com/18F/state-faq/pull/1 and https://github.com/18F/state-faq/pull/8 have draft answers.  The former PR is still outstanding, the latter is merged.

Also, the google doc has a comment from yours truly; but it's a tad philosophical compared to the above which are more concrete.

**Comment by mgwalker** [comment]
Closed by #8
